name: Job Alerts

on:
  schedule:
    - cron: "*/5 * * * *"   # Run every 5 minutes
  workflow_dispatch:         # Allow manual runs from Actions tab

jobs:
  run-job-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job alert script
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python main.py

      # ✅ Optional: persist seen_jobs.json so duplicates aren't re-emailed
      - name: Commit updated seen_jobs.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_jobs.json
          git commit -m "Update seen jobs [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
