name: Job Alerts

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # manual run option

permissions:
  contents: write  # <-- allows updating files like seen_jobs.json

jobs:
  run-job-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job alert script
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python main.py

      - name: Commit updated seen jobs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_jobs.json
          git commit -m "Update seen jobs [skip ci]" || echo "No changes to commit"
          git push
